### ISSUE TITLE
Rename main branch to release

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamuluswebsite#107]
**Is your feature request related to a problem? Please describe.**
Currently the name "main" is misleading.

**Describe the solution you'd like**
I suggest to rename main to something like release to clarify what the branch is for.

**Describe alternatives you've considered**
We could also name it live or published.

**Comment by gilgongo** [comment]
Fine by me (BTW what does the tag "good first issue" mean?)

**Comment by ann0see** [comment]
It means that an issue like that is good for newcomers who would like to start contributing. 
https://github.blog/2020-01-22-browse-good-first-issues-to-start-contributing-to-open-source/

**Comment by ann0see** [comment]
> Fine by me

Ok. So we will rename it to release.

(Will do it this evening)

**Comment by ann0see** [comment]
Ok. Done. I've now added a few permissions to specific groups who could in theory now have push access to the translation branch. @jamulussoftware/trreviewers
I propose to only allow one trreviewer (= main translator with push access) per language.

**Comment by trebmuh** [comment]
>  I propose to only allow one trreviewer (= main translator with push access) per language.

@ann0see I propose myself for the French translation.

**Comment by ann0see** [comment]
I also think that you would be capable of doing that (as far as I remember you're the official Jamulus Software translator and experienced with translation), but I think you have to discuss it with your translation group. They must be ok with it.

**Comment by trebmuh** [comment]
Yes, I'm the translator for the software.
@gegeweb : you OK?

**Comment by trebmuh** [comment]
Yes, I'm the translator for the software and I've got experience with audio software translation (Ardour, Hydrogen, Audacity, Qtractor, LMMS, and a few dozen more).

@gegeweb @Saimyx: you're OK?

**Comment by gegeweb** [comment]
> @gegeweb @Saimyx: you're OK?

Yes.

**Comment by trebmuh** [comment]
@ann0see : we can leave a bit of time to @Saimyx to answer, but just letting you know that he said in another thread that his time was limited and he wasn't able to keep up with all the discussion/PR here. I'm then unsure if he's going to answer here in this very thread.

**Comment by ann0see** [comment]
Ok. Let's give him some time.

**Comment by gegeweb** [comment]
> Ok. Let's give him some time.

I think it is clear here: https://github.com/jamulussoftware/jamuluswebsite/issues/38#issuecomment-734993464

IMHO, no need to wait for his answer, it's an implicit agreement. ;)

**Comment by ann0see** [comment]
Ok. I will wait until tomorrow evening.

**Comment by trebmuh** [comment]
> I think it is clear here: [#38 (comment)](https://github.com/jamulussoftware/jamuluswebsite/issues/38#issuecomment-734993464)

That was the one I was thinking about. Thank you to have found it and to have put the link here.
