### ISSUE TITLE
[Feature] Implement search engine

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamuluswebsite#17]
**Is your feature request related to a problem? Please describe.**
Currently it's quite challenging to find pages which are not in the navigation. Therefore I suggest to add a search function. Since jekyll is static, we can't do server side search.

**Describe the solution you'd like**
I looked into https://learn.cloudcannon.com/jekyll/jekyll-search-using-lunr-js/ which might work
**Describe alternatives you've considered**
https://github.com/christian-fei/Simple-Jekyll-Search

Breaks the site
**Additional context**
None

**Comment by gilgongo** [comment]
This is a good idea if we can do it. Also reminds me we should probably have a look at how the site's doing in terms of Google's indexes too at some point,

**Comment by ann0see** [comment]
> we should probably have a look at how the site's doing in terms of Google's indexes

Yes. I'd suggest to have a look at the Google Search Console.

Concerning this issue, I will start working on it.
