### ISSUE TITLE
[Translate] German translation

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamuluswebsite#2]
# Language you want to translate to
German
# Description
Translate most important parts of the wiki to german. This includes: Getting Started (Already done), Setup Windows (done)/Mac (done)/Linux (done), Troubleshooting Client and Hardware Setup.
Is anybody interested in taking over? I'd like to focus on development, not translation.

**Comment by SmuSmu** [comment]
I will take over

**Comment by ann0see** [comment]
Great!

**Comment by ann0see** [comment]
@SmuSmu 

There are new changes to the translation:

See:
https://github.com/jamulussoftware/jamuluswebsite/pull/158

Unfortunately you couldn't be added to the translators GitHub team.
