### ISSUE TITLE
"Link GNU free software definition" (not only french)?

### ISSUE THREAD

**Issue by gegeweb** [jamulussoftware/jamuluswebsite#42]
As I did for the french translation (see #41) of the home page say that Jamulus is free software and putting a link to the definition of the GPL license shoold be great!

**Comment by trebmuh** [comment]
I support this idea. Could you make a PR against the EN version?

**Comment by gegeweb** [comment]
> I support this idea. Could you make a PR against the EN version?

I can do it.
What is the right method? I think I can now work directly on this repository (thank you!).
- create a new 'fix-42' branch
- submit the merger request with the description 'W: [en] fix #42' or 'W: [en] add links to GPL definition (#42)'.

**Comment by ann0see** [comment]
Yes W: [en] add links to GPL definition (#42) would be great. 

@gilgongo said

> OK so we could change the current text in the "Jamulus is Open Source" section on the home page from:

"Jamulus is licensed under the (GPL, General Public License)."

to:

"Jamulus is free software licensed under the GPL."

So people who know what GNU is all about can see that Jamulus is GPL licenced, while those who don't can click the link to "free software" and find out. The French always have the best ideas!

**Comment by gegeweb** [comment]
My merge request is ready to be submited, see below my proposal:

```html
    <h2>Jamulus is a <a href="https://www.gnu.org/philosophy/free-sw.en.html" target="_blank" rel="noreferrer" title="What is free software?">free software</a></h2>
    <p>
      Ideas? Found a bug? Want to contribute? Since Jamulus is a <a href="https://www.gnu.org/philosophy/free-sw.en.html" target="_blank" rel="noreferrer" title="What is free software?">free software</a> you can help us! Find the project on <a href="https://sourceforge.net/projects/llcon/" target="_blank" rel="noreferrer">SourceForge</a> and the <a
        href="https://github.com/corrados/jamulus" target="_blank" rel="noreferrer">source code on GitHub</a>!
      Jamulus is licensed under the (<a href="http://www.gnu.org/licenses/gpl-2.0.html" target="_blank" rel="noreferrer">GPL,
        GNU General Public License</a>).
    </p>
```

**Comment by ann0see** [comment]
Yeah. That's even better.

**Comment by gegeweb** [comment]
OK, I do the merge request.

**Comment by gegeweb** [comment]
> OK, I do the merge request.

I think i've missed something, or i can't work directly here:

```
$ git commit -a -m 'W: [en] add links to free software definition (#42)'
[fix-42 40e967b] W: [en] add links to free software definition (#42)
 1 file changed, 4 insertions(+), 4 deletions(-)
108B-GNIEL:jamuluswebsite gerald$ git push origin fix-42
Enter passphrase for key '/Users/gerald/.ssh/id_rsa': 
ERROR: Permission to jamulussoftware/jamuluswebsite.git denied to gegeweb.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by ann0see** [comment]
Yes. You need to open a PR from your repo. Writing access is disabled to keep track of changes on GitHub

**Comment by gegeweb** [comment]
@ann0see said
> Yes. You need to open a PR from your repo. Writing access is disabled to keep track of changes on GitHub via PRs

OK, before do that i need to clean the 'main' branch on my repo before create the fix branch.
I shouldn't have merged my 'french-translation' branch!
I don't know how to resynchronize my 'main' branch to the original repository so as not to include the French translation files. Git can drive me crazy sometimes! ;)

I need to go to work at the office, i'll have time this afternoon.

**Comment by ann0see** [comment]
Ok. No problem. You can create a new branch which is in sync with the current main branch. I haven't checked it but I think it works by fetching this repo with git fetch

Maybe this works:
https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/

**Comment by gilgongo** [comment]
Just a minor thing, the syntax of the original text is wrong in English. The brackets are for the acronym only, so it should be "GPL (GNU Public Licence)"

BTW I'd remove the stuff in brackets anyway if we are having a link to "what is free software" because anyone who doesn't know what GNU is not going to know what a public licence is - that's the point of the French suggestion isn't it? So things can be shorter and more informative.

**Comment by ann0see** [comment]
Yeah. I think that's better.

**Comment by gegeweb** [comment]
@gilgongo say

> BTW I'd remove the stuff in brackets anyway if we are having a link to "what is free software" because anyone who doesn't know what GNU is not going to know what a public licence is - that's the point of the French suggestion isn't it? So things can be shorter and more informative.

The French suggestion comes from the wording of the original documentation: "Jamulus is Open Source".
Yes Jamulus is "Open Source" *because it is _free software_ under GPL* license. Free softwares are by definition "Open Source", but "Open Source" softwares are not necessarily free softwares. ;)

It is this point that I think is important to clarify, people often make confusion.

**Comment by trebmuh** [comment]
Wouldn't the correct naming in English be "FOSS" (Free or Open Source Software) then?

**Comment by ann0see** [comment]
Yeah. I think so

**Comment by gilgongo** [comment]
@gegeweb Yes, that's a good point. So should we change the header of that section on the home page to say "Jamulus is Free" and the wording in English then becomes (as @trebmuh  says):

"Jamulus is [free software](https://www.gnu.org/philosophy/free-sw.en.html) (FOSS) licensed under the [GPL](http://www.gnu.org/licenses/gpl-2.0.html)."

**Comment by gegeweb** [comment]
> Yes, that's a good point. So should we change the header of that section on the home page to say "Jamulus is Free" and the wording in English then becomes

OK, I update my MR.

**Comment by gilgongo** [comment]
I forgot to put this change into the translation branch, so I think it'll have to wait until the release after this one.

**Comment by ann0see** [comment]
Can this be closed?

**Comment by gegeweb** [comment]
> Can this be closed?

Yes for me. Since it's merged on the `change` branch.

I still think it should also be included in the `translation` branch and that we should already include it in the translations. ;)

**Comment by ann0see** [comment]
> I still think it should also be included in the translation branch and that we should already include it in the translations. ;)

The current process doesn't allow it (since I think we will do a bit of restructuring after the french translation and the blog is finished). It makes translations much easier if we don't merge anything after the translations have started. 

But we can of course discuss it in #31
