### ISSUE TITLE
[Bug] Broken links

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamuluswebsite#43]
https://jamulus.io/de/wiki/Client-Troubleshooting
- (1:5847) 'ASIO4All..' => https://jamulus.io/de/wiki/Installation-for-Windows#setting-up-asio4all (HTTP 200 but missing anchor)

https://jamulus.io/de/wiki/Hardware-Setup
- (1:8171) 'client i..' => https://jamulus.io/de/wiki/Installation-for-Linux#configure-jack-with-qjackctl (HTTP 200 but missing anchor)

https://jamulus.io/de/wiki/Server-Linux
- (1:6848) 'Get the ..' => https://jamulus.io/de/wiki/Installation-for-Linux#get-jamulus-sources (HTTP 200 but missing anchor)
- (1:6934) 'dependen..' => https://jamulus.io/de/wiki/Installation-for-Linux#install-dependencies (HTTP 200 but missing anchor)
- (62:2672) 'More inf..' => https://jamulus.io/de/wiki/Compiling#the-headless-build-flag (HTTP 200 but missing anchor)

https://jamulus.io/de/wiki/Server-Rpi
- (1:5778) 'Get the ..' => https://jamulus.io/de/wiki/Installation-for-Linux#get-jamulus-sources (HTTP 200 but missing anchor)
- (1:5864) 'dependen..' => https://jamulus.io/de/wiki/Installation-for-Linux#install-dependencies (HTTP 200 but missing anchor)
- (1:6347) 'default ..' => https://jamulus.io/de/wiki/Installation-for-Linux#compile-this-bad-boy (HTTP 200 but missing anchor)

https://jamulus.io/de/wiki/Server-Win-Mac
- (1:8363) 'private ..' => https://jamulus.io/de/wiki/Choosing-a-Server-Type#3-central (HTTP 200 but missing anchor)

https://jamulus.io/de/wiki/Tips-Tricks-More
- (14:792) 'https://..' => https://jamulus.io/de/wiki/David%20Savinkoff (HTTP 404)

https://jamulus.io/es/wiki/Client-Troubleshooting
- (1:5870) 'la secci..' => https://jamulus.io/es/wiki/Installation-for-Windows#setting-up-asio4all (HTTP 200 but missing anchor)

https://jamulus.io/es/wiki/Getting-Started
- (1:10457) 'nota sob..' => https://jamulus.io/es/wiki/Getting-Started#having-trouble-cant-keep-in-time (HTTP 200 but missing anchor)

https://jamulus.io/es/wiki/Hardware-Setup
- (1:8304) 'guía de ..' => https://jamulus.io/es/wiki/Installation-for-Linux#configure-jack-with-qjackctl (HTTP 200 but missing anchor)

https://jamulus.io/es/wiki/Installation-for-Linux
- (11:2414) 'Obtén Ja..' => https://jamulus.io/es/wiki/Installation-for-Linux#get-jamulus-sources (HTTP 200 but missing anchor)
- (11:2508) 'instrucc..' => https://jamulus.io/es/wiki/Installation-for-Linux#compile-this-bad-boy (HTTP 200 but missing anchor)

https://jamulus.io/es/wiki/Running-a-Server
- (1:6359) 'Regla Nú..' => https://jamulus.io/es/wiki/Getting-Started#having-trouble-cant-keep-in-time (HTTP 200 but missing anchor)
- (1:7032) 'Regla Nú..' => https://jamulus.io/es/wiki/Getting-Started#having-trouble-cant-keep-in-time (HTTP 200 but missing anchor)

https://jamulus.io/es/wiki/Server-Linux
- (1:6765) 'Get the ..' => https://jamulus.io/es/wiki/Installation-for-Linux#get-jamulus-sources (HTTP 200 but missing anchor)
- (1:6851) 'dependen..' => https://jamulus.io/es/wiki/Installation-for-Linux#install-dependencies (HTTP 200 but missing anchor)
- (48:1224) 'recordin..' => https://jamulus.io/es/wiki/Server-Win-Mac#recording (HTTP 200 but missing anchor)
- (62:2672) 'More inf..' => https://jamulus.io/es/wiki/Compiling#the-headless-build-flag (HTTP 200 but missing anchor)

https://jamulus.io/es/wiki/Server-Rpi
- (1:5757) 'Obtén la..' => https://jamulus.io/es/wiki/Installation-for-Linux#get-jamulus-sources (HTTP 200 but missing anchor)
- (1:5845) 'dependen..' => https://jamulus.io/es/wiki/Installation-for-Linux#install-dependencies (HTTP 200 but missing anchor)
- (1:6362) 'instrucc..' => https://jamulus.io/es/wiki/Installation-for-Linux#compile-this-bad-boy (HTTP 200 but missing anchor)

https://jamulus.io/es/wiki/Tips-Tricks-More
- (14:893) 'https://..' => https://jamulus.io/es/wiki/David%20Savinkoff (HTTP 404)

https://jamulus.io/fr/wiki/Hardware-Setup
- (1:8179) 'client i..' => https://jamulus.io/fr/wiki/Installation-for-Linux#configure-jack-with-qjackctl (HTTP 200 but missing anchor)

https://jamulus.io/fr/wiki/Installation-for-Linux
- (11:2734) 'instruct..' => https://jamulus.io/fr/wiki/Installation-for-Linux#compiler-jamulus (HTTP 200 but missing anchor)
- (11:3940) 'serveur ..' => https://jamulus.io/fr/wiki/Server-Linux#serveur-sans-iug (HTTP 200 but missing anchor)

https://jamulus.io/fr/wiki/Running-a-Server
- (1:6367) 'Rule Num..' => https://jamulus.io/fr/wiki/Getting-Started#having-trouble-cant-keep-in-time (HTTP 200 but missing anchor)
- (1:6947) 'follow R..' => https://jamulus.io/fr/wiki/Getting-Started#having-trouble-cant-keep-in-time (HTTP 200 but missing anchor)

https://jamulus.io/fr/wiki/Server-Linux
- (1:6856) 'Get the ..' => https://jamulus.io/fr/wiki/Installation-for-Linux#get-jamulus-sources (HTTP 200 but missing anchor)
- (1:6942) 'dependen..' => https://jamulus.io/fr/wiki/Installation-for-Linux#install-dependencies (HTTP 200 but missing anchor)

https://jamulus.io/fr/wiki/Server-Rpi
- (1:5786) 'Get the ..' => https://jamulus.io/fr/wiki/Installation-for-Linux#get-jamulus-sources (HTTP 200 but missing anchor)
- (1:5872) 'dependen..' => https://jamulus.io/fr/wiki/Installation-for-Linux#install-dependencies (HTTP 200 but missing anchor)
- (1:6355) 'default ..' => https://jamulus.io/fr/wiki/Installation-for-Linux#compile-this-bad-boy (HTTP 200 but missing anchor)

https://jamulus.io/fr/wiki/Tips-Tricks-More
- (14:792) 'https://..' => https://jamulus.io/fr/wiki/David%20Savinkoff (HTTP 404)

https://jamulus.io/it/wiki/Client-Troubleshooting
- (1:6148) 'ASIO4All..' => https://jamulus.io/it/wiki/Installation-for-Windows#setting-up-asio4all (HTTP 200 but missing anchor)

https://jamulus.io/it/wiki/Command-Line-Options
- (3:1566) 'See note' => https://jamulus.io/it/wiki/Choosing-a-Server-Type#3-central (HTTP 200 but missing anchor)

https://jamulus.io/it/wiki/Hardware-Setup
- (1:8472) 'client i..' => https://jamulus.io/it/wiki/Installation-for-Linux#configure-jack-with-qjackctl (HTTP 200 but missing anchor)

https://jamulus.io/it/wiki/Installation-for-Linux
- (12:2585) 'ottenere..' => https://jamulus.io/it/wiki/Installation-for-Linux#get-jamulus-sources (HTTP 200 but missing anchor)
- (12:2673) 'istruzio..' => https://jamulus.io/it/wiki/Installation-for-Linux#compile-this-bad-boy (HTTP 200 but missing anchor)

https://jamulus.io/it/wiki/Running-a-Server
- (1:6660) 'Rule Num..' => https://jamulus.io/it/wiki/Getting-Started#having-trouble-cant-keep-in-time (HTTP 200 but missing anchor)
- (1:7240) 'follow R..' => https://jamulus.io/it/wiki/Getting-Started#having-trouble-cant-keep-in-time (HTTP 200 but missing anchor)

https://jamulus.io/it/wiki/Server-Linux
- (1:7149) 'Get the ..' => https://jamulus.io/it/wiki/Installation-for-Linux#get-jamulus-sources (HTTP 200 but missing anchor)
- (1:7235) 'dependen..' => https://jamulus.io/it/wiki/Installation-for-Linux#install-dependencies (HTTP 200 but missing anchor)

https://jamulus.io/it/wiki/Server-Rpi
- (1:6079) 'Get the ..' => https://jamulus.io/it/wiki/Installation-for-Linux#get-jamulus-sources (HTTP 200 but missing anchor)
- (1:6165) 'dependen..' => https://jamulus.io/it/wiki/Installation-for-Linux#install-dependencies (HTTP 200 but missing anchor)
- (1:6648) 'default ..' => https://jamulus.io/it/wiki/Installation-for-Linux#compile-this-bad-boy (HTTP 200 but missing anchor)

https://jamulus.io/it/wiki/Server-Win-Mac
- (1:8664) 'private ..' => https://jamulus.io/it/wiki/Choosing-a-Server-Type#3-central (HTTP 200 but missing anchor)

https://jamulus.io/it/wiki/Tips-Tricks-More
- (14:792) 'https://..' => https://jamulus.io/it/wiki/David%20Savinkoff (HTTP 404)

https://jamulus.io/wiki/Tips-Tricks-More
- (14:792) 'https://..' => https://jamulus.io/wiki/David%20Savinkoff (HTTP 404)

Stats:
    9682 links
     227 destination URLs
     257 URLs ignored
      46 warnings
       5 errors

**Comment by gilgongo** [comment]
What does "missing anchor" mean here?

**Comment by ann0see** [comment]
It means that the page which the link points to exists but not the headline (html id) it should jump to.

**Comment by gilgongo** [comment]
OK. So how do we fix that exactly in the .md files? Does the markdown syntax support it?

**Comment by ann0see** [comment]
Yes. The markdown syntax supports it. But it can only be fixed if the sites are correctly translated. I will do a new check right before the next release.

**Comment by ann0see** [comment]
Now part of #175
