### ISSUE TITLE
 Server-Win-Mac.md : about system FW under MacOS or Windows.

### ISSUE THREAD

**Issue by gegeweb** [jamulussoftware/jamuluswebsite#50]
When I first worked on the French translation (no new merge request yet) of the `Server-Win-Mac.md` page, I noticed the lack of mention about application firewalls.

On both systems, if the system firewall is active, at the first use of the server (GUI) an alert asks if you want to allow incoming connections for the application.
Of course, you have to confirm for it to work.

So I had a note like the following for the both: (my english may be no good)

-----

* **Windows users** - Start the server using the entry for "Jamulus server" in the Windows start menu.  
_Note: If you have an alert asking you to allow incoming connections for the Jumulus application, you must awnser yes to the question_

* **Macintosh users** - Double-click the "Jamulus server" icon in Applications (assuming you put the files from the install there as per [these instructions](Installation-for-Macintosh)).  
_Note: If you have an alert asking you to allow incoming connections for the Jumulus application, you must awnser yes to the question_

----

**Comment by gilgongo** [comment]
Probably better if we just say ,"Your system may ask you to open your firewall for Jamulus." and leave it at that. OSes (and third party anti-malware systems of which there are many) change all the time. Saying something like, "you must answer yes to the question" is bound to confuse somebody (or indeed annoy them, as I have been criticised for saying firewalls should be opened - some people like only to open them when running Jamulus). 

BTW the reason I didn't mention this in the docs was that I assumed most people would just click "OK" as they do on all dialogues. But I could be wrong so we should perhaps say something.

**Comment by ann0see** [comment]
Any updates on this? Should we add it or not?

For me on Windows 10 with Bitdefender, I didn't have a popup at all, same on macOS.

**Comment by trebmuh** [comment]
> "Your system may ask you to open your firewall for Jamulus."

Sounds good to me and is better since written this way, it could apply to all OSes (hence, we can just write it once).

**Comment by ann0see** [comment]
@gegeweb or @trebmuh can you open a PR to changes on this?

**Comment by trebmuh** [comment]
@ann0see against the English version you mean?

**Comment by ann0see** [comment]
Yes.

**Comment by gene96817** [comment]
I haven't be following this thread. I just noticed the comment of Dec 13. Be aware some users will be tricked by the existence of two firewalls. One in their computer and one in their router.

**Comment by gilgongo** [comment]
Moving to discussion until we can get a resolution on this. 

EDIT: Doesn't seem to be available for some reason. Closing instead.
