### ISSUE TITLE
Improvement for CONTRIBUTING.md

### ISSUE THREAD

**Issue by gegeweb** [jamulussoftware/jamuluswebsite#59]
Actual version of `CONTRIBUTING.md` is verry short!

----
# Contribute

Thanks for your support! Please open a pull request on GitHub!

----

I based myself on this rule when starting to work on the French translation, you can see what kind of misunderstanding it caused! ;)

I propose (i could open a MR if you agree) something like (not sure for my english!):

----
# Contribute to the documentation

Thanks for your support! You're welcome!

* First, take a look at the [issues](https://github.com/jamulussoftware/jamuluswebsite/issues) to check if there already one on the same subject.  
If yes, you can join the discussion adding your comment.  

* If no, start by openning a [new issue](https://github.com/jamulussoftware/jamuluswebsite/issues/new/choose) with your proposal.

* Then, you can submit your merge request with your adds or changes following the rules explained [here](https://jamulus.io/wiki/Contribution) and below:
  * If not doing yet, fork this repository
  * create a new branch from the up to date `changes` branch
  * make your changes
  * push the new branch into your repository
  * submit the merge request linking to the opened issue from your branch to the `changes`branch.
  * wait for the review and the merge…

**DO NOT MERGE YOUR WORK** into your local `changes`branch, only keep it in sync by pooling from the remote Jamulus repository.
**DO NOT WORK ON** your local `changes` branch, always works from a new branch.  
If the `changes`branch is modified before submitting your request, keep the local `changes`branch in sync by pooling from it, merge the local `changes` branch into your working branch, resolve conflicts and then push your changes and create the merge request.

Please note that all the discussions are in English. If it is not you're native language and are not fluent with it, it can dissuade you. Don't be afraid, you can use [DeepL](https://www.deepl.com) wich make good translations as a help support.

**Comment by ann0see** [comment]
Yes. The contribution file has to be updated. I think we should explain how the merge process works too (all changes go to the changes branch, if you want to translate something, you have to do it on the translation branch, small typos can "go live" right away and therefore should be made to the "main" branch). 

I don't understand why you can't work on your local "changes" branch? I don't see the problem there since it's on your branch.

**Comment by gilgongo** [comment]
I take a different view as per https://github.com/jamulussoftware/jamuluswebsite/issues/60#issuecomment-731719320 (BTW why are there two tickets for this?) The first two instructions should be enough. But I hope that 99% of people would have no idea what a PR is in any case,  so it may not matter :-)  

(Well, assuming it doesn't put them off contributing at all if they think they will expected to use git!)

**Comment by gegeweb** [comment]
> BTW why are there two tickets for this?

This one for the `CONTRIBUTING.md`file in the repository (source code of the site/doc).
#60 for `Contribution.md`on the website. The `README;md`is linking to the first files.

**Comment by gegeweb** [comment]
> I don't understand why you can't work on your local "changes" branch? I don't see the problem there since it's on your branch.

This can be a problem if you are working on two fixes or two separate files and you want to make an MR for each one.
My experience with Git has led me to do so.
One branch per subject.
In this case only the files concerned are in the MR and the following commits until the merge.

**Comment by trebmuh** [comment]
We should have 2 different paragraphs, one for contributing text/page/typo_fix/... to the original (English) files, and one for contributing to a translation. With an advice to not mix between both.

I've written several rule of thumb [on this comment](https://github.com/jamulussoftware/jamuluswebsite/issues/31#issuecomment-730496044) that we should take here.

**Comment by gegeweb** [comment]
I think this file should look like [the one in the source code of the software](https://github.com/corrados/jamulus/blob/master/CONTRIBUTING.md).

This is, in my opinion, a more technical guide on how to proceed since we're at the level of the website source code (please, stop saying "wiki", it's not a wiki anymore ;)).
Logically, we arrive here, after reading the documentation on the website. Possibly after going through the forum.

It should describe the procedures for a translation, an improvement request or a fixing.
It should also give technical help (basic usage) for those not familiar with git, and development tools if the person opening the ticket is asked to submit an MR.

I'll leave it up to you to debate it and decide what should be in it.
What matters to me as I work on the French translation (not to get back to it) is the content of `Contribution.md` on the website (#60). 

It's early in the morning here, so have a good day!

**Comment by ann0see** [comment]
# Contribute to the documentation
We really appreciate your support! Please have a look at the [issues page on GitHub](https://github.com/jamulussoftware/jamuluswebsite/issues) and check if anybody already raised an issue with the same topic.

If this is the case, please subscribe to the issue and explain your proposal.

If that's not the case, please open a [new issue](https://github.com/jamulussoftware/jamuluswebsite/issues/new/choose), select which type of issue it is and describe your issue.

If you want to open a Pull Request (after having described and discussed your proposal), have a look at the [Contribution page on the website](https://jamulus.io/wiki/Contribution). Keep in mind that your changes (if they are not just typos) might have to wait until everything is translated. We will bundle them (if everything is allright) with other changes and upload multiple changes in one bulk to jamulus.io.
## I don't know GitHub. What do I need to know?
If you aren't comfortable with Pull Requests, commits, etc. just open an issue. We will then care about your changes. If you want to do the changes on your own and open a Pull Request, follow this instructions:
1. Fork this repo (there's a fork button on the top right of the page)
2. Create a new branch from the up to date `changes` branch
3. Make your changes
4. If you did the changes offline, push the new branch into your repository
5. Submit your Pull Request (merge it to the `changes` branch), give a short description of your changes and link the issue you opened
6. Wait for a review and a merge.

Hint (for git): DO NOT MERGE YOUR WORK into your local `changes` branch, only keep it in sync by pooling from the remote Jamulus Website repository. Create a new branch for your proposed changes.
If the `changes` branch is modified before submitting your request, keep the local `changes` branch in sync by pooling from the official one, merge the local changes branch into your working branch, resolve conflicts, push your changes and create the Pull Request.

Please note that discussions should be kept in English. Don't be afraid, if you don't speak English fluently. You can use [DeepL](https://www.deepl.com) which might be able to translate your language to English.

**Comment by trebmuh** [comment]
LGTM

**Comment by ann0see** [comment]
@gilgongo any thoughts?

**Comment by ann0see** [comment]
@trebmuh 

Yes. We should clarify our process too.

**Comment by ann0see** [comment]
@gegeweb I've added your DO NOT MERGE [...] proposals to my small correction. I think it could also be done by a git rebase (but I'm not sure).

**Comment by gilgongo** [comment]
I remain slightly confused by this. 

If the intention is to link to this page from some page on the website, then I think it needs a re-write to remove duplicate and potentially confusing or even conflicting information, and put it into the same written style as the rest of the English site. 

If the intention is simply to document our translation process and give that link to others when needed (so just have it in the list on /wiki/) then it can stay as is (although personally I'd remove some of the noise and overly-specific things).
