### ISSUE TITLE
[Translate] - IT Coordination

### ISSUE THREAD

**Issue by dzpex** [jamulussoftware/jamuluswebsite#61]
Hi ann0see. I had problem with my pc in the next day i will continue it trans.

In these days i had thinked that if there are any change in original language page is necessary create an allert for replicate the changes in other langua page .....

How do you think about?

**Comment by ann0see** [comment]
We've restructured the translation process. Have a look at the translation branch and only translate the changes there (everything else will be for the next release)

**Comment by ann0see** [comment]
Mainly the changes can be found here: https://github.com/orgs/jamulussoftware/teams/translators

**Comment by ann0see** [comment]
Closed in favor of a GitHub discussion #1
