### ISSUE TITLE
Jamulus code signing – Jamulus safety

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamuluswebsite#62]
**Describe the bug**
During my SEO checking around Jamulus I came across the question if Jamulus is safe. If you download it from the original source (SourceForge) or compile it on your own, it is (there’s no virus/malware included). 

I think people search for this because of the missing code signature (Windows defender Smartscreen, macOS gatekeeper).

 I‘ve made the Windows & Mac install pages a bit clearer (see changes branch).

Could you please check the wording and make it a bit clearer?

**Comment by gilgongo** [comment]
I guess https://github.com/corrados/jamulus/issues/550 may not happen after all then :-(

Those clarifications look OK I think.

**Comment by ann0see** [comment]
Yeah. That's a pitty

**Comment by ann0see** [comment]
Close

**Comment by ann0see** [comment]
Note to self: https://user-images.githubusercontent.com/20726856/99886658-adc69800-2c3e-11eb-938e-7c4609f855b6.png

For german translation in changes branch
