### ISSUE TITLE
[Bug] Incorrect structure for navigation

### ISSUE THREAD

**Issue by gegeweb** [jamulussoftware/jamuluswebsite#64]
As you can see in the screenshot below (using w3m) a new list item is created after the `h3`title.
The 'li' should not be closed after the 'h3' and not reopeened before the unordered list for submenu.

<img width="610" alt="Capture d’écran 2020-11-24 à 13 14 34" src="https://user-images.githubusercontent.com/9108457/100097208-be545980-2e5c-11eb-95ca-eb81c83343bc.png">

Here is the output of the good structure (I'll open a MR) with the fix below:
<img width="206" alt="Capture d’écran 2020-11-24 à 13 57 13" src="https://user-images.githubusercontent.com/9108457/100097561-f9ef2380-2e5c-11eb-9637-4a34628dc187.png">

<img width="296" alt="Capture d’écran 2020-11-24 à 14 15 43" src="https://user-images.githubusercontent.com/9108457/100099374-a4684600-2e5f-11eb-9ac4-59d027bd1e53.png">

```html
<aside id="gnav" class="fx-col-100-xs fx-col-25-m">
	{% include langselect.html %}
	<nav id="mnv">
		<ul>
			{% if site.data.navigation.nav[0] %} {% for item in site.data.navigation.nav %} {% if item.url %}
			<li>
				<h3><a href="{{ item.url | relative_url }}" class="{% if subentry.url == page.url %}selected{% endif %}">{{ item.title }}</a></h3>
				{% else %}
				<li>
					<h3>{{ item.title }}</h3>
					{% endif %} {% if item.subfolderitems[0] %}
					<ul>
						{% for entry in item.subfolderitems %}
						<li><a href="{{ entry.url }}" class="{% if entry.url == page.url %}selected{% endif %}">{{ entry.page }}</a> {% if entry.subsubfolderitems[0] %}
							<ul>
								{% for subentry in entry.subsubfolderitems %}
								<li><a href="{{ subentry.url }}" class="{% if subentry.url == page.url %}selected{% endif %}">{{ subentry.page }}</a></li>
								{% endfor %}
							</ul>
							{% endif %}
						</li>
						{% endfor %}
					</ul>
				</li>
				{% endif %} {% endfor %} {% endif %}
		</ul>
	</nav>
</aside>
```

**Comment by ann0see** [comment]
Interesting. I will look at your pr and the new structure this evening.

**Comment by ann0see** [comment]
Ok. Understood the problem now. Will merge it
