### ISSUE TITLE
Refer to "macOS" not "Macintosh" in the documentation

### ISSUE THREAD

**Issue by gegeweb** [jamulussoftware/jamuluswebsite#88]
Good Morning to all (It's morning here at this time),

sorry in advance for my english here (not checked if it is good), there is an emergency! ;)

I'm working on the french translation. At this time working on `fr-Server-Win-Mac.md`before launch reviewing.

And I've a **big problem to follow the rule and keep in close** to the original english version (**In fact, I really can't**) because **using « Macintosh » is wrong**. First, since 1998 this family computers is named « Mac ». But the most important thing is that « Macitosh » or « Mac » **is for designing a family of personal computers**, not an OS.
Using « Macintosh » is as using « PC » without take care about the operating system (Windows can be installed on a Mac (since Intel processor), GNU/Linux and *BSD too…).

So "Instalation for Macintosh" is not correct and even more "Installation for Windows[^1] and Macintosh".

That **must be** "Installation for Windows an macOS" or "Installation for Windows and Mac OS X or macOS" if Jamulus works on Apple OS < 10.15. Everywhere « Macintosh » is used.

See the [Wikipédia French page](https://fr.wikipedia.org/wiki/Macintosh) : « _Ne doit pas être confondu avec Mac OS, macOS ou Adresse MAC_ »
**Not to be confused with Mac OS, macOS or MAC address**

In the near futur we probably should take care about processor too because the new M1 processor. I don't know if Jamulus have been compiled and tested on a Mac with macOS and M1 processor. (waiting for feedback here https://github.com/corrados/jamulus/issues/749)

So for the French version, we must make an exception to the rule and fix the "bug" already, EN version must be fixed too. That's a « _bug_ » with a high priority that must be fixed quickly as possible! (in all the branchs)

[^1]: about Windows: perhaps should be « Windows 10 and later » (doesn't works on Windows 7 and early)
As you see we don't say « Installation for PC » here (Mac family are PC (Personal Computer) too)

**Notes:**
* _aside, I think an exception to the rule should also be make for the Index page_
* _there is other forgot or mistake about macOS or Mac OS X, but that can be fixed later, no high priority_

**Comment by gegeweb** [comment]
> In the near futur we probably should take care about processor too because the new M1 processor. I don't know if Jamulus have been compiled and tested on a Mac with macOS and M1 processor.

We could add a warning: « Jamulus have not be tested yet on macOS running on a Mac M1 computer » it it is the case.

**Comment by gegeweb** [comment]
See #81 for proposal (in French)

**Comment by trebmuh** [comment]
From what I understand (I'm not a mac user), I'd agreed with the issue here. @gilgongo can you please confirm? Should we ask corrados tp confirm/infirm?


> So for the French version, we must make an exception to the rule and fix the "bug" already,

I disagree. If I agree with you that this can be seen as a documentation bug, I don't feel it's such an urgent bug that we have to break the rule. It is my understanding that most people will anyway understand that the documentation is talking about macOS.


> EN version must be fixed too.

Yes.


> That's a « bug » with a high priority that must be fixed quickly as possible! (in all the branchs)

It's not of "high priority" for my point of view. No cat will be killed, no jamulus server will not be overloaded, nobody will get a +135dB hiss in the headphone,...etc. As far as I understand the problem, the only output it can produce would be a very few people unable to install Jamulus. "very few" because we are talking here about:
1. people on a Mac computer
2. people on a Mac computer without macOs
2. people on a Mac computer without macOs who want to use Jamulus
4. people on a Mac computer without macOs who want to use Jamulus and who aren't understanding that the documentation is talking about MacOS rather than MacIntosh

If I'm not wrong and understand the issue at hand here, how many people does that represent? I'd roughly think that this is about a few persons, or even few dozen of persons around the world.

My opinion is that can wait the next cycle of doc writing & translations (a few weeks IIUC).

**Comment by gegeweb** [comment]
> t's not of "high priority" for my point of view.

I may have exaggerated a bit. ;) Sorry for that.
But this is an important point for me.
Even more so with the arrival of the M1 processor.

In fact we can't use and build Jamulus on PPC Macintosh, even if they are running Mac OS X.

The transmitted information are not correct or incomplete. 
We should also mention from which Jamulus version can be used.
If 10.15 minimum, so macOS only.

As we should mention "Windows 10 or later".

**Comment by gegeweb** [comment]
And as I explain above, you could run Linux, Windows, or FreeBSD on a "Mac family computer".

**Comment by ignotus666** [comment]
I think it should go in the 'changes' branch and get updated in the translations with all the rest of the updates when the time comes. I don't reckon it's something that will cause much grief beyond a raised eyebrow.

**Comment by gegeweb** [comment]
> I think it should go in the 'changes' branch and get updated in the translations with all the rest of the updates when the time comes.

I am not opposed to that. ;)
So, I'll open a fix MR for the EN version if @gilgongo agree and update the #81 to keep close to the actual EN version in the `translation` branch. @trebmuh, you agree?

**Comment by trebmuh** [comment]
I agree with the method, but I'm unsure about the different fixes you're proposing here. Can you please summarize them in such a form then, it's easy to read here in this thread (without reading at other issue/PR/comments)?

**Comment by gegeweb** [comment]
> I agree with the method, but I'm unsure about the different fixes you're proposing here. Can you please summarize them in such a form then, it's easy to read here in this thread (without reading at other issue/PR/comments)?

* On the Menu "Macintosh" -> "Mac OS X" or "macOS" already used on `Getting-Started` for the button.
* "Installation for Macintosh" -> "Installation on Mac OS X and macOS" (`Installation-for-Macintosh`)
* "For Windows and Macintosh user" -> "For Windows and macOS user" (`Running a Server`)
* "Installation for Windows and Macintosh" -> "Installation for Windows and Mac OS X or macOS" (`Server-Win-Mac`)
* "Macintosh users" -> "macOS users"  (`Server-Win-Mac`)
* `Getting-Started`(depend of thee feedback about https://github.com/corrados/jamulus/issues/749) add a warning/note like this :

_(**Note:** Jamulus has not yet been tested with MacOS Big Sure on the new Mac M1, if you have successfully compiled and/or tested its use on this platform please let us know by opening an issue [on the Jamulus repository](https://github.com/corrados/jamulus/issues))_

That's all I think.

**Comment by trebmuh** [comment]
OK, thanks for summarizing this.

I'm not sure about the 4th line. "_Installation for Windows and Mac OS X or macOS_" it reads/sounds cumbersome to me. Is that really necessary? (Once again, I'm not a mac user so I might miss some obvious things.

**Comment by gegeweb** [comment]
> I'm not sure about the 4th line. "_Installation for Windows and Mac OS X or macOS_" it reads/sounds cumbersome to me. Is that really necessary? (Once again, I'm not a mac user so I might miss some obvious things.

That's to be exhaustive because Jamulus (as mentioned in Getting Started) run on Mac OS X 10.11 (El Captain) and later. It is named macOS since 10.12 (Sierra). So, we can use only macOS (as on actual Getting Started page).

**Comment by gegeweb** [comment]
And on `Server-Win-Mac`, there is no the introduction "Make sure you read the Getting Started page." as on Installation Windows and Installation for Macintosh. So remind the minimum required versions of both systems on this page could be a good idea.
Like this :
_Note: Jamulus Server run on Windows 10 or higher and Mac OS X El Capitan (v10.11) or higher_ 
With the warning about new Mac M1 too. As long as we don't know if Jamulus is running on this platform.

**Comment by gilgongo** [comment]
The current Mac operating system is macOS. It was originally named "Mac OS X" until 2012 and then "OS X" until 2016. 

In the docs we say Jamulus runs on Macs running El Capitan (v10.11) or later, which was released in September 30, 2015. So implying it will run on Mac OS X is wrong, no?

But if we want to be precise, should we not just refer to it in the docs consistently as "macOS"? 

BTW in your comment https://github.com/jamulussoftware/jamuluswebsite/issues/88#issuecomment-734921486 where are you proposing to put the message about testing on M1? If somebody finds a bug in Jamulus with that, they can just report it in the normal way like anything else. We shouldn't be cluttering up the docs with noise like this.

**Comment by gegeweb** [comment]
@gilgongo 

> @gegeweb In your comment [#88 (comment)](https://github.com/jamulussoftware/jamuluswebsite/issues/88#issuecomment-734921486) where are you proposing to put the message about testing on M1? If somebody finds a bug in Jamulus with that, they can just report it in the normal way like anything else. We shouldn't be cluttering up the docs with noise like this.

Sorry, it is not clear, at the `Getting-Started` page. And perhaps at the `Server-Win-Mac`too.
That is a new processor, a lot of app doesn't works on it at this time. And I don't know if there is a compatibilty mode as in the transition from PPC to Intel.

**Comment by gegeweb** [comment]
> In the docs we say Jamulus runs on Macs running El Capitan (v10.11) or later, which was released in September 30, 2015. So implying it will run on Mac OS X is wrong, no?

It is named macOS since 10.12 (Sierra). But yes "macOS" only is good. There should not be many 10.11's left in use.

**Comment by gilgongo** [comment]
OK so can we just make all references to the Macintosh operating system say simply "macOS". Let's do that. 

> at the Getting-Started page. And perhaps at the Server-Win-Mac too.

The "design principle" for those pages is to keep them as simple as possible. If we know of a significant bug with Jamulus and M1 then we can say that, but until then if somebody gets a bug with anything they can just report it in the normal way.

**Comment by trebmuh** [comment]
> The "design principle" for those pages is to keep them as simple as possible

_Thinking out loud here_: if we don't want to be too much precise in the doc, but want to stay consistent. What about using "_Mac_" alone? After all, we're doing the same with "_Linux_". We're not having precise pages or page titles for each version of each Linux distributions.

And if users have question about a precise Apple/Mac OS version, they can still use the forum, the issue, or another way of communicating with the community, isn't?

Thoughts?

**Comment by gegeweb** [comment]
> _Thinking out loud here_: if we don't want to be too much precise in the doc, but want to stay consistent. What about using "_Mac_" alone?

I think "macOS" is better. Because "Mac" designate the "Mac family computer" (like "Macintosh"). macOS is the name of Apple's OS since Sierra (10.12) so it make sens to use It. There is "Hackintosh" which are not "Mac family computer" but "PC" (not a lot, I agree). And "macOS" is already used on Getting Started page and metadata. We can forgot "Mac OS X".

**Comment by gilgongo** [comment]
I think just as long as we use the same word consistently, that's probably OK.

**Comment by ann0see** [comment]
> And I don't know if there is a compatibilty mode as in the transition from PPC to Intel.

Yes there is. It's called Rosetta 2: https://appleinsider.com/inside/rosetta-2

**Comment by gilgongo** [comment]
Can anyone braver than me search/replace and pull request everything in the changes branch for anything called "Macintosh", "Mac", "OSX" etc. and make it simply "macOS"?

**Comment by gegeweb** [comment]
> Can anyone braver than me search/replace and pull request everything in the changes branch for anything called "Macintosh", "Mac", "OSX" etc. and make it simply "macOS"?

If there are no other volunteers, I am ready to do so.

**Comment by gegeweb** [comment]
> > Can anyone braver than me search/replace and pull request everything in the changes branch for anything called "Macintosh", "Mac", "OSX" etc. and make it simply "macOS"?
> 
> If there are no other volunteers, I am ready to do so.

@gilgongo Only on the EN version or in every pages include translation?

**Comment by gilgongo** [comment]
Ah good point - guess it's everything, since it would be language independent.

**Comment by trebmuh** [comment]
> Ah good point - guess it's everything, since it would be language independent.

I wouldn't go that way. It can happen that, even if it looks like a drop in replacement, manual translation editing is needed for some languages.

**Comment by gilgongo** [comment]
OK sure. So @gegeweb unleash your power on the the EN version only.

**Comment by gegeweb** [comment]
> OK sure. So @gegeweb unleash your power on the the EN version only.

OK.

For Getting Started Page i propose:
**A computer** running either **Windows 10**, **MacOS X** El Capitan (v10.11) or higher **macOS**, or **Linux**.
Because macOS start with Sierra (10.12). Agree?

**Comment by gegeweb** [comment]
I didn't touch the Sound Devices page. Because user's contributions.

Should be done.

**Comment by ann0see** [comment]
> A computer running either Windows 10, MacOS X El Capitan (v10.11) or higher macOS, or Linux.

Better:

A computer running either Windows 10, macOS (MacOS X El Capitan (v10.11) or higher), or Linux.

**Comment by gegeweb** [comment]
> Better:
> 
> A computer running either Windows 10, macOS (MacOS X El Capitan v10.11 or higher), or Linux.

I've pushed a new commit with this proposal,  it's better.
