### ISSUE TITLE
[Feature] Make wiki structure more understandable by using a link which shows parent pages (breadcrumb)

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamuluswebsite#9]
**Is your feature request related to a problem? Please describe.**
Currently if you are on a wiki page for the first time, it might be confusing if you clicked through multiple pages and are lost in the structure. e.g. if you are on the Choosing-a-server-type page you might be confused where you are and don't know how to come back since the navigation doesn't link this page.

**Describe the solution you'd like**
It would be great to have a breadcrumb or something similar like in the current issue.

**Describe alternatives you've considered**
Add a breadcrumb to every page manually (this is not a clean solution)
**Additional context**
See this:
![Screenshot_2020-10-25 corrados jamulus](https://user-images.githubusercontent.com/20726856/97116999-5b5a9000-1701-11eb-8dc2-d57f57a14910.png)

**Comment by gilgongo** [comment]
I think this may be hard to automate, and not having the breadcrumbs is a bit of a problem. Now that we have the changes branch, I'll see if I can just add them in manually until we can have a better solution.

**Comment by ann0see** [comment]
I think we have two ways to add breadcrumbs:

1. loop through all pages and build a structure by front matter (not recommended and probably messy)
2. generate a folder structure and build the sites with this structure (e.g. https://jekyllcodex.org/without-plugin/breadcrumbs/)

**Comment by ann0see** [comment]
For 2 see the breadcrumb branch. But it does mean a restructuring of the pages (but I don't think that's a big problem)

**Comment by gilgongo** [comment]
I was thinking maybe making a special "breadcrumb" link style and putting it over the H1 if we can keep the H1 in the same place. Or maybe put it in the blue header bar next to the logo? 

Also BTW there is the question of whether you repeat the name of the current page in the leaf of the breadcrumb or not. People do it both ways. On the old wiki I did a sort of "summary title" for the leaf to re-enforce the meaning of the H1.  One thing about automating the breadcrumbs is whether we can control that, and also whether we get "redundant" breadcrumbs on pages that don't need them.

**Comment by ann0see** [comment]
Ok. So I suggest you add them if my PR to main is merged.

**Comment by ann0see** [comment]
Fixed by @gilgongo
