### ISSUE TITLE
Thoughts about information architecture 2.0

### ISSUE THREAD

**Issue by gegeweb** [jamulussoftware/jamuluswebsite#93]
The two "Troubleshooting" page are like "FAQ", by the way "FAQ" is already used in the description of some internal links.

What about renaming these "Frequently asked questions (FAQ) – client" and "Frequently asked questions (FAQ) – server"?

Then we open the door to no technical problems with questions I've seen in other places like:

_"What is the best practice when joining a jam session?"_ (for example)

**Comment by gilgongo** [comment]
I don't think there's a problem with renaming them to FAQ as you suggest, and adding non-technical issues too. 

But this is one of the things we need to deal with if we're going to have the new "community" section. How do we decide what sort of content goes where? Is "_What is the best practice when joining a jam session?_" a FAQ thing or a community thing? Tips & Tricks seems to be a list of links to other people's stuff, which is good (and if they want to "donate" it to the community section to help our SEO at some point, that would be even better!), but it's clearly also implicated in the confusion about where people go to get what content. 

The more I think about this, the more it seems like we need to produce a "version 2" of the Jamulus information architecture. The current "version 1" is what Volker and I built from almost scratch back in March and it was a rushed job in the face of an avalanche of users so it may not be fit for purpose any more.

How about we merge Troubleshooting with the FAQs and Tips and Tricks into one "officially maintained" area, while the new "community" area is "unofficial" stuff which may overlap but will hopefully be broader in scope and more linkable.

**Comment by gegeweb** [comment]
> The current "version 1" is what Volker and I built from almost scratch back in March and it was a rushed job in the face of an avalanche of users so it may not be fit for purpose any more.

So, congratulations! Because I've find this doc clear and very useful for me when I had discover Jamulus.
Maybe just a bit of a tortuous way for navigate sometimes.
Jamulus is so intuitive that I didn't read the "Software Manual" page the first time I used it.

**Comment by ann0see** [comment]
@gilgongo 

Yes, I do agree that we might need a new information structure. 

1. Clarify who is responsible for what (I can't merge every language PR since I don't understand e.g. Italian) --> introduce merge rights for some translators (at least for the translation branch)
2. Rethink the Manual
3. There should be other things but I don't remember them yet

**Comment by ann0see** [comment]
I've re-thought some parts of the wiki. See the simplify branch and a pr I will shortly open. It's not really a big change (in fact only another page and a few small changes)

**Comment by ann0see** [comment]
> I don't think there's a problem with renaming them to FAQ as you suggest, and adding non-technical issues too.

No problem.

> How about we merge Troubleshooting with the FAQs and Tips and Tricks into one (or two, split client and server?) "officially maintained" area, while the new "community" area is "unofficial" stuff which may overlap but will hopefully be broader in scope and more linkable.

Agree.

**Comment by ann0see** [comment]
Ok documenting the current process:

> Clarify who is responsible for what (I can't merge every language PR since I don't understand e.g. Italian) --> introduce merge rights for some translators (at least for the translation branch) 

not yet done

> Rethink the Manual

#110 maybe solved it a bit

Some new thoughts:

We should clarify that

1. A normal user shouldn't need to visit GitHub unless he has a feature request
2. A developer only finds feature requests on GitHub and doesn't need to search through SourceForge, Facebook, whatever

#60

**Comment by gilgongo** [comment]
I think at least some of these things have been done, and if we have further ideas we have them in Discussions, so closing.
