### ISSUE TITLE
Strange wording in en-Linux-Install-Script.md

### ISSUE THREAD

**Issue by gegeweb** [jamulussoftware/jamuluswebsite#94]
In the end of `en-Linux-Install-Script.md`, in the paragraph about improvements for the script there is wording that take time to me to understand the meaning for a good translation (and i'm not already sure): 

strange wording in emphase below:

----
The script can ask in the very beginning for which linux distribution the installation script should be called.
This can be tested with the command `lsb_release`

_With the `lsb_release` command the command returns the distribution specific information about a Linux distro._
_With a `grep` command with regular expression the variable `DISTRO` and `LINVERSION`._
E.g. the Ubuntu based systems return with the command the following information.

---

Seems there is a repetition in the first and missing something in the second.

I would suggest: [edited]

---
With the `lsb_release` command wich returns the specific informations about the distro on Linux.
With a `grep` command using regular expressions for the variable `DISTRO` and `LINVERSION`.

---

Translated in French:

--- 
Avec la commande `lsb_release` qui retourne les informations spécifiques à la ditribution sous Linux.  
Avec la commande `grep`et en utilisant des expressions rationnelles pour les variables `DISTRO` et `LINVERSION`.

---

**Comment by gegeweb** [comment]
There is also typo, missing `"` here:

```md
* `DISTRO="Ubuntu` for a Ubuntu or Linux Mint
* `DISTRO="Debian` for a Debian or Raspian Linux
* `DISTRO="Fedora` for a Fedora Linux
```

Should be
```
* `DISTRO="Ubuntu"` for a Ubuntu or Linux Mint
* `DISTRO="Debian"` for a Debian or Raspian Linux
* `DISTRO="Fedora"` for a Fedora Linux
```

I'll do the fix in the French version.

I can submit the fix for the EN version too, in this case, in wich branch? `changes`?

**Comment by gegeweb** [comment]
And just after, for :

```md
Furthermore if the installation is dependent of the release the variable `LINVERSION` is introduced but is currently not used. In the Ubuntu if statement there is an example how version dependent installation calls can be performed.
```
It's ambiguous, I suggest to enclose the statement `if` in "`":
```md
Furthermore if the installation is dependent of the release the variable `LINVERSION` is introduced but is currently not used. In the Ubuntu `if` statement there is an example how version dependent installation calls can be performed.
```

**Comment by ann0see** [comment]
I don't know who is in charge of the install script, but it would be great if he changed it. 

In fact, this would also be something for the new "blog" or community tricks page.

**Comment by trebmuh** [comment]
I'm only reading this thread after I've reviewed the French translation of this page.
Doing so, I've saw a few typo in the English version and I already made #97 for that.
This PR contains a fix for the first issue you're mentionning here @gegeweb . Please check if that's fine for you.

Now, I've added the missing `"` character you're mentionning in your second message here. Good eye!

I agree here too with your third point (the `if`) and am adding it right now to the PR too.

**Comment by gilgongo** [comment]
> In fact, this would also be something for the new "blog" or community tricks page.

Agreed: https://github.com/jamulussoftware/jamuluswebsite/pull/97#issuecomment-735250685

**Comment by ann0see** [comment]
#171 is the new pr

**Comment by trebmuh** [comment]
@ann0see closing here then?

**Comment by ann0see** [comment]
Yes closed
